CREATE TABLE Sales (
	[Id]        UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[SaleDt]    DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
	[ProductId] UNIQUEIDENTIFIER NOT NULL REFERENCES Products(Id),
	[Quantity]  INT              NOT NULL DEFAULT 1,
	[ManagerId] UNIQUEIDENTIFIER NOT NULL REFERENCES Managers(Id),
	[DeleteDt]  DATETIME         NULL
);